# Generated by Django 5.2.6 on 2025-09-13 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_time', models.CharField(max_length=100)),
                ('nome_jogo', models.CharField(max_length=100)),
                ('ano_criacao', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('apelido', models.CharField(blank=True, max_length=50)),
                ('nivel', models.IntegerField()),
                ('tipo', models.CharField(max_length=20)),
                ('imagem', models.URLField()),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemons', to='team_builder.time')),
            ],
        ),
    ]
